# config.yaml
program: src/models/train_model_sweep.py
method: random
name: sweep
metric:
  goal: minimize
  name: train_batch_loss
parameters:
  batch_size: 
    values: [16,32]
  lr:
    min: 0.0001
    max: 0.01
  epochs:
    values: [5, 10, 15]